const modulePrefix = 'inviteUsersToChat/';

export const FIND_ALL_USERS_NOT_PRESENTED_IN_CHAT = `${modulePrefix}FIND_ALL_USERS_NOT_PRESENTED_IN_CHAT`;
export const FIND_ALL_USERS_NOT_PRESENTED_IN_CHAT_SUCCESS = `${modulePrefix}FIND_ALL_USERS_NOT_PRESENTED_IN_CHAT_SUCCESS`;
export const FIND_ALL_USERS_NOT_PRESENTED_IN_CHAT_FAILED = `${modulePrefix}FIND_ALL_USERS_NOT_PRESENTED_IN_CHAT_FAILED`;

export const INVITE_USERS_TO_CHAT = `${modulePrefix}INVITE_USERS_TO_CHAT`;
export const INVITE_USERS_TO_CHAT_SUCCESS = `${modulePrefix}INVITE_USERS_TO_CHAT_SUCCESS`;
export const INVITE_USERS_TO_CHAT_FAILED = `${modulePrefix}INVITE_USERS_TO_CHAT_FAILED`;
